apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo-backend
  name: demo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-backend
    spec:
      containers:
      - image: sentientmonkey/hello
        name: hello
        resources: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo-frontend
  name: demo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-frontend
    spec:
      containers:
      - image: sentientmonkey/hello-frontend
        name: hello-frontend
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo-backend
  name: demo-backend
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo-backend
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo-frontend
  name: demo-frontend
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demo-frontend
  type: ClusterIP
status:
  loadBalancer: {}
