apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  rules:
    - http:
        paths:
          - path: /api
            backend:
              serviceName: demo-backend
              servicePort: 8080
          - path: /
            backend:
              serviceName: demo-frontend
              servicePort: 3000
